### ISSUE TITLE
Multiple resources per database

### ISSUE THREAD

**Issue by gka** [holidayextras/jsonapi-store-relationaldb#22]
This might be a stupid question, but I don't understand why each resource aka. table needs to get its own database.

The main reason why I want to use a relational database instead of a simpler store is that I my app is dealing with multiple, related resources. And creating one database per resource is not very practicable.

**Comment by mmiller42** [comment]
:+1: I concur. A little bit confused here. Does the jsonapi-store-relationaldb create one table per database?!

**Comment by pmcnr-hx** [comment]
When I last chatted to @theninj4 about this he had some compelling arguments in favour of this design decision. We are currently pursuing more actively other document stores, so we won't probably be looking into adding support for this soon. Pull requests are welcome.

**Comment by mmiller42** [comment]
I'm gonna fork this and mess with it a bit to see. If there are good reasons not to use the same database for multiple resources, please let me know, because I don't want to do something that'd be a poor design choice simply as a matter of convenience.

Looks like there should be a fairly simple way to use the same database and enforce unique table names, as well as share Sequelize instances as opposed to opening up new connections for each resource type. I'd imagine doing that gets network intensive as you approach having dozens of different resources.

**Comment by theninj4** [comment]
@mmiller42 you raise a great point about connection limits in some common scenarios.

Our original thought process (which was biased towards business requirements) was to have separate database instances for each resource. The original implementation achieved this by simply namespacing resources into different databases - we had one testing database but the resources were as distant as possible. After reading your comments I think you're right, merging them to save on connections is a great shout.

As a heads up we're currently pursuing other data storage modules due to the hassle of database migrations to enable schema changes. We absolutely welcome contributors to this project.

Thanks for taking the time to comment about the connection volumes :+1:

**Comment by mmiller42** [comment]
Cool!

When you say "other data storage modules," are you talking about an alternative to Sequelize, or do you mean working on other jsonapi-stores besides the relationaldb store?

If it's the former, I know of two others: [Waterline](https://github.com/balderdashy/waterline) (an excellent, database-agnostic ORM that provides the same interface for essentially any persistence store -- but at some performance and feature cost) and [Bookshelf](http://bookshelfjs.org/) (another relational SQL ORM like Sequelize but, so I hear, somewhat more stable). I'm not an expert in either of them, but in my experience the last month with Bookshelf at work, I'm starting to think that just writing dialect-agnostic SQL is more realistic a lot of the time than finagling an ORM. If you go that route, [Knex](http://knexjs.org/) is a good tool for chaining together SQL queries without adhering to a specific dialect and it does have a schema builder although I don't know how good it is at migrations.

Just on a side note to you guys -- I love your project. I've messed with a number of Node.js REST API frameworks and libraries before discovering the JSON:API spec. This is an excellent project that eliminates a lot of the redundant hassle of "build the CRUD endpoints, document them, implement them on the client" endless cycle. I'm planning on pitching your framework to my employer as a means of standardizing our cross-process and cross-product APIs.

**Comment by theninj4** [comment]
We're looking into other database technologies - we moved to using MongoDB in production to enable us to iterate faster, however after consulting with some database guys with impressive resumes we're leaning towards either Elasticsearch (data store is written and open source, although we don't use it in production yet) or AWS's DynamoDB (significant WIP at the moment). 

I'd recommend getting comfortable with these codebases - we will fix any bugs that cause us trouble in production, but beyond that this project and the others fall under the MIT license.

**Comment by mauvm** [comment]
I'm running into the same problem. Will changing https://github.com/holidayextras/jsonapi-store-relationaldb/blob/a6f1d3c9fe7120523357d50c53d872d411aba72b/lib/sqlHandler.js#L29 to `self.sequelize = new Sequelize(self.config.database || resourceConfig.resource, self.config.username, self.config.password, {` be sufficient?

**Comment by pmcnr-hx** [comment]
Hi @mauvm, I'm afraid it's a bit more involved than that. We're in the process of reviewing and merging #25 which will add support for multiple resources per database. Please feel free to test that branch and feedback.

**Comment by pmcnr-hx** [comment]
This has now been addressed by #25. We'll be doing a release soon that will fully support the latest `jsonapi-server` release but if you don't use `Boolean` properties in your resources `v1.1.0` will still work correctly with the latest `jsonapi-server` and allow multiple resources per database.
